image: python:3.6-slim-buster

stages:
  - build
  - test
  - deploy

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    WORKON_HOME: "$CI_PROJECT_DIR/venv"

default:
  before_script:
    - pip install pipenv

build:
  stage: build
  script:
    - apt update -qy
    - apt install -y libpq-dev
    - env VIRTUALENV_COPIES=1 pipenv install --ignore-pipfile --dev
  artifacts:
    paths:
      - .cache/pip
      - venv/

test_pytest:
  stage: test
  script:
    - pipenv run pytest

heroku:
  image: ruby:latest
  stage: deploy
  inherit:
    default: false
  dependencies: []
  script:
    - apt update -qy
    - apt install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=hospital-organize-me --api-key=$HEROKU_API_KEY
  only:
    - master
