stages:
    - build
    - test
    - deploy

variables:
    # do not change those by hand!
    # use admin script to bump versions
    PYTHON_VERSION: "3.9.1"
    NODE_VERSION: "14.15.3"

.pipenv_job: &pipenv_job
    image: python:$PYTHON_VERSION
    before_script:
        - pip install pipenv
    variables:
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
        WORKON_HOME: "$CI_PROJECT_DIR/venv"

.python_formatter_linter_jobs_base: &python_formatter_linter_jobs_base
    stage: test
    dependencies:
        - install_pipenv
    <<: *pipenv_job

.node_formatter_linter_jobs_base: &node_formatter_linter_jobs_base
    image: node:$NODE_VERSION
    stage: test
    dependencies:
        - install_node

install_pipenv:
    stage: build
    <<: *pipenv_job
    script:
        - env VIRTUALENV_COPIES=1 pipenv sync --dev
    artifacts:
        paths:
            - .cache/pip
            - venv/
        expire_in: 1 day

install_node:
    image: node:$NODE_VERSION
    stage: build
    script:
        - yarn install
    artifacts:
        paths:
            - node_modules/
        expire_in: 1 day

prettier:
    <<: *node_formatter_linter_jobs_base
    script:
        - yarn run check-format

eslint:
    <<: *node_formatter_linter_jobs_base
    before_script:
        - yarn run check-eslint-config
    script:
        - yarn run lint

flake8:
    <<: *python_formatter_linter_jobs_base
    script:
        - pipenv run flake8

black:
    <<: *python_formatter_linter_jobs_base
    script:
        - pipenv run black . --check

isort:
    <<: *python_formatter_linter_jobs_base
    script:
        - pipenv run isort . --check

shellcheck:
    image: koalaman/shellcheck-alpine:stable
    stage: test
    dependencies: []
    script:
        - shellcheck $(find . -name *.sh)

shfmt:
    image: mvdan/shfmt:v3.2.2-alpine
    stage: test
    dependencies: []
    script:
        - shfmt -i 4 -ci -d $(find . -name *.sh)

heroku:
    image: ruby:3.0.0
    stage: deploy
    dependencies: []
    script:
        - apt update -qy
        - apt install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=hospital-organize-me --api-key=$HEROKU_API_KEY
    only:
        - tags
    except:
        - branches
