version: '3.7'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    command: pipenv run python manage.py runserver 0:8000
    volumes:
      - ./backend:/usr/src/app/backend
      - ./manage.py:/usr/src/app/manage.py
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    command: yarn serve
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    ports:
      - 8080:8080

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
