version: '3.7'

services:
  django:
    build: 
      context: .
      dockerfile: docker/django.Dockerfile
    command: docker/django_entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  vue:
    build:
      context: .
      dockerfile: docker/vue.Dockerfile
    command: docker/vue_entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 8080:8080

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
