version: "3.8"

services:
    django:
        image: registry.gitlab.com/jaolejnik/organize-me/django:latest
        build:
            context: .
            dockerfile: docker/django.Dockerfile
            args:
                - CORE_PYTHON_VER=${CORE_PYTHON_VER}
                - CORE_PIPENV_VER=${CORE_PIPENV_VER}
        command: docker/django_entrypoint.sh
        volumes:
            - .:/app
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - db

    vue:
        image: node:${CORE_NODE_VER}
        working_dir: /app
        command: docker/vue_entrypoint.sh
        volumes:
            - .:/app
        env_file:
            - ./.env
        ports:
            - 8080:8080
        depends_on:
            - django

    db:
        image: postgres:${CORE_POSTGRES_VER}
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env

volumes:
    postgres_data:
