version: '3.7'

services:
  web:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    command: pipenv run python manage.py runserver 0:8000
    volumes:
      - ./backend:/usr/src/app/backend
      - ./manage.py:/usr/src/app/manage.py
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
